version: '3.4'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: crypto-bug
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./docker/db/mysql/data:/var/lib/mysql
      - ./docker/db/mysql/log:/var/log
    ports:
      - "127.0.0.1:33065:3306"

  cryptobug-main:
    image: feraru/crypto-bug:v1.0
    env_file:
      - .env
    depends_on:
      - mysql